services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_DB: postgres12
      POSTGRES_PASSWORD: 6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      POSTGRES_USER: postgres
    image: postgres:16.2-bookworm
    networks:
      - default
    ports:
      - 5437:5432
    volumes:
      - ./persistence-data/temporal-postgresql-data:/var/lib/postgresql/data
  temporal:
    container_name: temporal
    links:
      - postgresql
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:1.28.0
    networks:
      - default
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.28
    networks:
      - default
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.39.0
    networks:
      - default
    ports:
      - 8180:8080

networks:
  default:
    external: true
    name: streamware_default
