name: streamware

include:
  - docker-compose.db.yml
  - docker-compose.kafka.yml
  - docker-compose.redis.yml
  - docker-compose.elastic.yml
  - docker-compose.proxy.yml
  - docker-compose.cassandra.yml
  - docker-compose.temporal.yml
  - docker-compose.services.yml
