services:
  messenger-engine:
    image: streamware/messenger-engine
    ports:
      - "9000:9000"
    environment:
      - NAME=A
      - APP_PORT=9000
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - REDIS_HOST=dragonfly
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - DB_TYPE=postgres
      - DB_HOST=localhost
      - DB_PORT=5430
      - DB_USERNAME=postgres
      - DB_PASSWORD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - DB_NAME=presence
      - DB_SYNCHRONIZE=true
    depends_on:
      - cassandra
    restart: on-failure

  auth:
    image: streamware/auth
    ports:
      - "8080:8080"
    environment:
      - NAME=Auth
      - SERVER_PORT=8080
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRATION=31556952 # in seconds, default is 24 hours
      - JWT_REFRESH_TOKEN_EXPIRATION=31556952 # in seconds, default 1 year
      - JWT_ISSUER=http://streamware.ir
      - JWT_AUDIENCE=http://streamware.ir
    depends_on:
      - postgres
    volumes:
      - "./keys/private_key.pem:/app/keys/private_key.pem"
      - "./keys/public_key.pem:/app/keys/public_key.pem"
    restart: on-failure
    networks:
      - kafka

  pulse-cast:
    image: streamware/pulse-cast
    ports:
      - "9090:8081"
    environment:
      - NAME=pulse-cast
      - SERVER_PORT=8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - REDIS_HOST=dragonfly
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - postgres-notify-hub
    restart: on-failure
    networks:
      - kafka

  messenger-rest-engine:
    image: streamware/messenger-rest-engine
    ports:
      - "8083:8083"
    environment:
      - NAME=messenger-rest-engine
      - SERVER_PORT=8083
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_KEYSPACE=messages
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on:
      - postgres-notify-hub
    restart: on-failure
    networks:
      - cassandra

  postgres-notify-hub:
    image: postgres:16.2-bookworm
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-notify-hub-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-hub
    networks:
      - postgres-pulse-cast

  postgres-presence:
    image: postgres:16.2-bookworm
    ports:
      - "5430:5432"
    volumes:
      - ./postgres-presence-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - POSTGRES_USER=postgres
      - POSTGRES_DB=presence

  postgres:
    image: postgres:16.2-bookworm
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth
    networks:
      - postgres

  pulse-cast-postgres:
    image: postgres:16.2-bookworm
    ports:
      - "5432:5432"
    volumes:
      - ./pulse-cast-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6jliq83an911t0h9rw34l4q73k4xvmen0jbvd2b5
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pulse-cast
    networks:
      - postgres

  cassandra:
    image: cassandra:5.0.3
    ports:
      - "9042:9042"
    volumes:
      - ./migrations/setup.sh:/usr/setup.sh
      - ./migrations/setup.cql:/usr/setup.cql
    entrypoint: ["/bin/bash", "-c"]
    command:
      - "chmod +x /usr/setup.sh &&
        nohup /usr/setup.sh &> /usr/setup.log &
        docker-entrypoint.sh cassandra -f"
    networks:
      - cassandra

  haproxy:
    image: haproxy:2.9-alpine
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - "./keys/private_key.pem:/app/keys/private_key.pem"
      - "./keys/public_key.pem:/app/keys/public_key.pem"
    ports:
      - "80:80"
    environment:
      - ISSUER=http://streamware.ir
      - AUDIENCE=http://streamware.ir
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:

networks:
  proxy:
    external: true
  kafka:
    driver: bridge
    external: true
  cassandra:
    driver: bridge
  postgres:
    driver: bridge
  postgres-pulse-cast:
    driver: bridge
