version: '3.8'
services:
  athena:
    # build: 
    #   context: ./Athena-Another-Clone
    #   dockerfile: Dockerfile
    image: ghcr.io/streamware/athena
    ports:
      - "9000:9000"
    environment:
      - SCYLLA_URI=cassandra:9042
    depends_on:
      - cassandra
    restart: on-failure

  artemis:
    # build: 
    #   context: ./Artemis
    #   dockerfile: Dockerfile
    image: ghcr.io/streamware/artemis
    ports:
      - "3001:3001"
    environment:
      - APP_PORT=3001
      - DATABASE_URL=
      - ACCESS_TOKEN_EXPIRATION=3600 # in seconds, default is 24 hours
      - REFRESH_TOKEN_EXPIRATION=31556952 # in seconds, default 1 year
      - ISSUER=http://streamware.co
      - AUDIENCE=http://streamware.co
    depends_on:
      - cassandra
    volumes:
      - './keys/private_key.pem:/app/keys/private_key.pem'
      - './keys/public_key.pem:/app/keys/public_key.pem'
    restart: on-failure

  swift-rest-engine:
    # build: 
    #   context: ./swify-rest-engine
    #   dockerfile: Dockerfile
    image: ghcr.io/streamware/swifty-rest-engine
    ports:
      - "3000:3000"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on:
      - cassandra
    restart: on-failure

  echo-server:
    image: "jmalloc/echo-server"
    ports:
      - "8080:8080"
    restart: on-failure

  cassandra:
    image: cassandra:4.1.0
    ports:
      - "9042:9042"
    volumes:
      - ./migrations/setup.sh:/usr/setup.sh
      - ./migrations/setup.cql:/usr/setup.cql
    entrypoint: ["/bin/bash", "-c"]
    command:
      - "chmod +x /usr/setup.sh &&
       nohup /usr/setup.sh &> /usr/setup.log &
       docker-entrypoint.sh cassandra -f"

  haproxy:
    image: haproxy:2.9-alpine
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - './keys/private_key.pem:/app/keys/private_key.pem'
      - './keys/public_key.pem:/app/keys/public_key.pem'
    ports:
      - "80:80"
    environment:
      - ISSUER=http://streamware.co
      - AUDIENCE=http://streamware.co
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true

  # postgres:
  #   image: postgres:16.1-alpine
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=S3cret
  #     - POSTGRES_USER=citizix_user
  #     - POSTGRES_DB=citizix_db

